### ISSUE TITLE
alert 단추색 통일시키기

### ISSUE THREAD

**Issue by kyj94** [petcarepedia/petcarepedia_v2#182]
- 확인버튼: #FFB3BD 
![image](https://github.com/petcarepedia/petcarepedia_v2/assets/130637272/176963b5-a155-41c0-ae10-9334d951d242)

- 취소버튼: #98DFFF
![image](https://github.com/petcarepedia/petcarepedia_v2/assets/130637272/a4359a4d-f802-45a1-b531-089b9418d752)

- 기본 버튼 색상 변경
success: function(rstate_result) {
                        if (rstate_result === "fail") { 
                            Swal.fire({
                                icon: 'error',
                                title: '신고 접수된 리뷰입니다',
                                text: '관리자 확인중 입니다. 잠시만 기다려 주세요.',
                                showConfirmButton: true,
                                didOpen: () => {
                                    const confirmButton = Swal.getConfirmButton();
                                    confirmButton.style.backgroundColor = '#98DFFF';
                                  }
                            }).then(function() {
                                location.reload();
                            });

![image](https://github.com/petcarepedia/petcarepedia_v2/assets/130637272/ad4f9765-12ea-40a2-b9e1-7de4f214575b)

**Comment by heynokimush** [comment]
confirmButtonColor:'#98dfff',
confirmButtonText:'확인'
